{application,brod,
             [{description,"Apache Kafka Erlang client library"},
              {vsn,"4.3.3"},
              {registered,[]},
              {applications,[kernel,stdlib,kafka_protocol]},
              {env,[]},
              {mod,{brod,[]}},
              {modules,[brod,brod_cg_commits,brod_client,brod_consumer,
                        brod_consumers_sup,brod_group_coordinator,
                        brod_group_member,brod_group_subscriber,
                        brod_group_subscriber_v2,brod_group_subscriber_worker,
                        brod_kafka_apis,brod_kafka_request,brod_producer,
                        brod_producer_buffer,brod_producers_sup,brod_sup,
                        brod_supervisor3,brod_topic_subscriber,
                        brod_topic_subscriber_cb_fun,brod_transaction,
                        brod_transaction_processor,brod_utils]},
              {licenses,["Apache License 2.0"]},
              {links,[{"Github","https://github.com/kafka4beam/brod"}]},
              {build_tools,["rebar3"]},
              {files,["src","include","rebar.config","rebar.config.script",
                      "README.md","LICENSE","NOTICE","Makefile"]}]}.
