{application,ex_aws_sqs,
             [{modules,['Elixir.ExAws.SQS','Elixir.ExAws.SQS.SaxyCollector',
                        'Elixir.ExAws.SQS.SaxyParser']},
              {optional_applications,[hackney,jason,saxy,sweet_xml]},
              {applications,[kernel,stdlib,elixir,logger,hackney,jason,saxy,
                             sweet_xml,ex_aws]},
              {description,"ex_aws_sqs"},
              {registered,[]},
              {vsn,"3.4.0"}]}.
